version: "3.9"
services:
    api:
        container_name: "api"
        restart: always
        build: .
        ports:
          - "8000:80"
        deploy:
          resources:
            limits:
              cpus: "2"
              memory: 2048M
        volumes:
          - /www/grabber-instagram/files:/www/files