version: "3.9"
services:
    instagram_api:
        container_name: "instagram_api"
        restart: always
        # Fix: use init or will be many chrome (defunct) which overflow process table and server freeze
        # https://docs.docker.com/engine/reference/run/#specify-an-init-process
        init: true
        build: .
        ports:
          - "3050:3050"
        cap_add:
          - SYS_PTRACE
        deploy:
          resources:
            limits:
              cpus: "2"
              memory: 2048M
        volumes:
          - /www/files/grabber-instagram:/www/files