version: "3.9"
services:
    instagram_api:
        container_name: "instagram_api"
        restart: always
        build: .
        ports:
          - "8000:80"
        cap_add:
          - SYS_PTRACE
        deploy:
          resources:
            limits:
              cpus: "2"
              memory: 2048M
        volumes:
          - /www/files/grabber-instagram:/www/files